# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 672991437b2480b3ef433723886115ed17b888d895e3e4297b1892306a13ab46752c1b6a3e0f72c7f437562e7debc8a4b364b7d5bc4c74368c1b2ff14000a948

test:
  secret_key_base: 2e9f27bc8e73ef41a1dea067232b475142a8c4646257be5c8fe5cdbaa60741441e9ed213355e8f7ec2505d9257d086678583cc89144bd79a2bf54fd1951e38a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
